### ISSUE TITLE
Add functionality for add operation

### ISSUE THREAD

**Issue by mayankshah1607** [IEEE-VIT/SimpleMath-Flask#1]
The scope of this issue is simple - complete the logic for performing add operation on calling a POST request at `/math/add`
Add relevant tests under test/test_app.py

**Comment by sameer-j** [comment]
Can you provide information about the input?

**Comment by mayankshah1607** [comment]
It could be an array of numbers in a json

**Comment by SriNandan33** [comment]
can you give the sample JSON please

**Comment by SriNandan33** [comment]
and can you assign this to me if no one is working on this please, can I take this up?

**Comment by Krishna-Sivakumar** [comment]
Can I work on this? I'm pretty familiar with JSON. @mayankshah1607

**Comment by sameer-j** [comment]
I am interested in working on this, thats y asked for input information. I hope I wont miss out on contributing to it just because I didnt explicitly asked

**Comment by mayankshah1607** [comment]
Hi! Thank you for showing interest. I have opened a new issue. Please do check it out - https://github.com/IEEE-VIT/SimpleMath-Flask/issues/15
