### ISSUE TITLE
Add functionality for division operation

### ISSUE THREAD

**Issue by GOPAL-YADAV-D** [IEEE-VIT/SimpleMath-Flask#104]
Implement the logic to handle addition operations when a `POST` request is made to the  `/math/division`  endpoint. Additionally, write appropriate test cases within the `test/test_app.py` file to validate this functionality.

**Comment by docjon09** [comment]
Hi, please assign this task to me.

**Comment by GOPAL-YADAV-D** [comment]
> Hi, please assign this task to me
Hello ,@docjon09 I have assigned the issue to you .Please stick with the contribution guidelines and update me with the progress.

**Comment by docjon09** [comment]
Hi @GOPAL-YADAV-D . What would be the name of the operands(numbers to be divided) in the POST request? Also, should I return the result as a JSON? If so, what should I keep its name as?

**Comment by GOPAL-YADAV-D** [comment]
> Hi @GOPAL-YADAV-D . What would be the name of the operands(numbers to be divided) in the POST request? Also, should I return the result as a JSON? If so, what should I keep its name as?

The request must be a JSON of the following format :

{
  data : {
                  param1: <value>,
                  ...
                  param<n>: <value>
            }
}
