### ISSUE TITLE
Add functionality for multiplication operation

### ISSUE THREAD

**Issue by GOPAL-YADAV-D** [IEEE-VIT/SimpleMath-Flask#105]
Implement the logic to handle addition operations when a `POST` request is made to the `/math/multiply` endpoint. Additionally, write appropriate test cases within the `test/test_app.py` file to validate this functionality

**Comment by swetha3456** [comment]
Hi, I'd like to work on this. Please assign it to me.

**Comment by badoolee** [comment]
Hi, i already worked on this but forgot to ask you to assign to me. i hope my pull request will be accepted.

**Comment by GOPAL-YADAV-D** [comment]
Hello,@badoolee  your PR is under review .But please make a note that next time get assigned first and then make a PR

**Comment by abhinab-choudhury** [comment]
Can you Assigned this issue to me

**Comment by GOPAL-YADAV-D** [comment]
> Can you Assigned this issue to me

@abhinab-choudhury ,This issue has been worked on please look out for other issues and get assigned
