### ISSUE TITLE
Add exponentiation functionality

### ISSUE THREAD

**Issue by GOPAL-YADAV-D** [IEEE-VIT/SimpleMath-Flask#106]
Implement the logic to handle addition operations when a `POST` request is made to the  `/math/exponentiation`  endpoint. Additionally, write appropriate test cases within the `test/test_app.py` file to validate this functionality.

**Comment by rabroldan** [comment]
Can I take tis one?

**Comment by swetha3456** [comment]
Hi, I'd like to work on this. Please assign it to me.

**Comment by GOPAL-YADAV-D** [comment]
Hello ,@swetha3456 I have assigned the issue to you .Please stick with the contribution guidelines and update me with the progress.
