### ISSUE TITLE
Add matrix-addition functionality 

### ISSUE THREAD

**Issue by GOPAL-YADAV-D** [IEEE-VIT/SimpleMath-Flask#107]
Implement the logic to handle addition operations when a `POST` request is made to the `/math/matrixaddition` endpoint. Additionally, write appropriate test cases within the `test/test_app.py`file to validate this functionality.

**Comment by docjon09** [comment]
Hi, please assign this task to me.

**Comment by DNA5769** [comment]
Could you assign me this issue

**Comment by DNA5769** [comment]
Could you please review my PR #109

**Comment by GOPAL-YADAV-D** [comment]
Your PR is Good to Go . I will merge it .Thank you for your participation in our Project . Also look for our other projects and Don't forget to Star our repo

**Comment by DNA5769** [comment]
Thanks ❤️
