### ISSUE TITLE
Add matrix-multiplication functionality

### ISSUE THREAD

**Issue by GOPAL-YADAV-D** [IEEE-VIT/SimpleMath-Flask#110]
Implement the logic to handle addition operations when a `POST `request is made to the `/math/matrixmultiplication` endpoint. Additionally, write appropriate test cases within the `test/test_app.pyfile` to validate this functionality.

**Comment by AimenYaseen** [comment]
I want to contribute to this task...
Please assign this to me.

**Comment by GOPAL-YADAV-D** [comment]
Hello ,@AimenYaseen I have assigned the issue to you .Please stick with the contribution guidelines and update me with the progress.
