### ISSUE TITLE
Add functionality to solve quadratic equation

### ISSUE THREAD

**Issue by GOPAL-YADAV-D** [IEEE-VIT/SimpleMath-Flask#112]
Implement the logic to handle addition operations when a `POST` request is made to the `/math/quadraticequation` endpoint. Additionally, write appropriate test cases within the`test/test_app.py` file to validate this functionality.

**Comment by AimenYaseen** [comment]
Hey! I want to contribute in this issue.

**Comment by GOPAL-YADAV-D** [comment]
Hello ,@AimenYaseen I have assigned the issue to you .Please stick with the contribution guidelines and update me with the progress.

**Comment by GOPAL-YADAV-D** [comment]
@AimenYaseen ,Please update me with progress on the issue .

**Comment by AimenYaseen** [comment]
@GOPAL-YADAV-D 
I am working on it. I will create PR tomorrow.

**Comment by AimenYaseen** [comment]
@GOPAL-YADAV-D 
I have shared the PR. Please check. And let me know if any change is required.
