### ISSUE TITLE
Organize and Optimize Code

### ISSUE THREAD

**Issue by AimenYaseen** [IEEE-VIT/SimpleMath-Flask#123]
Currently, all endpoints and tests are in one file. It makes it difficult to read and debug code.

**Comment by AimenYaseen** [comment]
@GOPAL-YADAV-D 
I want to work on this... If you allow I can organize code in different files in a package.

**Comment by GOPAL-YADAV-D** [comment]
Yes , please go ahead

**Comment by AimenYaseen** [comment]
@GOPAL-YADAV-D 
I noticed, 83 pull requests are pending. Please review and merge them. So that I start refactoring on the entire code. It will be useless if I refactor current code and change contribution guidelines as many issues are build on previous guidelines.

**Comment by GOPAL-YADAV-D** [comment]
@AimenYaseen , You  may ignore the pull requests which were made before 2023 .As for the current one's after the conflicts have been taken care of we will review them.

**Comment by AimenYaseen** [comment]
ok
