### ISSUE TITLE
Add functionality for any maths operation

### ISSUE THREAD

**Issue by mayankshah1607** [IEEE-VIT/SimpleMath-Flask#15]
You can add routes in the API that perform any maths operation - from simple multiplication, to even calculating matrix dot products.

The request must be a JSON of the following format : 
```
{
  data : {
                  param1: <value>,
                  ...
                  param<n>: <value>
            }
}
```

The response must a JSON of the following format:

```
{
     result: <value>,
     meta: {
     <any relevant meta data here>
     }
}
```

Make sure to add relevant unit tests .
Comment below with the maths operation you will be taking up to avoid clashes with other developers. :)

**Comment by Krishna-Sivakumar** [comment]
I will take this issue on

**Comment by WillDaSilva** [comment]
I'll add support for matrix dot product

**Comment by Krishna-Sivakumar** [comment]
@mayankshah1607 Can numpy be used?
Edit: I have made a PR for addition, multiplication and division.

**Comment by SriNandan33** [comment]
I am going to add funcionality for **power**, **root**.

**Comment by SriNandan33** [comment]
> I am going to add funcionality for **power**, **root**.

https://github.com/IEEE-VIT/SimpleMath-Flask/pull/25#issue-323606632

**Comment by SriNandan33** [comment]
I have given PR for power, root https://github.com/IEEE-VIT/SimpleMath-Flask/pull/25#issue-323606632
Kindly review it please

**Comment by SriNandan33** [comment]
#25

**Comment by SriNandan33** [comment]
I have given a PR for **power, root** functionality #25 , please review it.

**Comment by conk3r353** [comment]
I will work on logarithms.

**Comment by rushivarun** [comment]
How will the data for division of two numbers be provided?

**Comment by Krishna-Sivakumar** [comment]
> How will the data for division of two numbers be provided?

It is in the above format, you could add some docstrings on how to use it.
